name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  port: 
  description: 'run port 80:80'
    required: true
    default: '80:80'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.port }}
