name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  user: 
    description: 'hello github'
    required: true
    default: 'github'
  name:
    description: "hello actions"
    required: true
    default: "actions"
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.port }}
