name: 'My Docker GitHub Action'
description: 'A simple GitHub Action that runs inside a Docker container'
inputs:
  args1:
    description: 'First argument for the script'
    required: true
    default: 'Hello'
  args2:
    description: 'Second argument for the script'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'  
  args:
    - ${{ inputs.args1 }}
    - ${{ inputs.args2 }} 
