name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  num1: 
    description: 'my num1'
    required: true
    default: 40 
  num2:
    description: 'my num2'
    required: true
    default: 50
outputs:
  sum:
    description: 'sum'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.num1 }}
    - ${{ inputs.num2 }}
