name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  sum1: 
    description: 'my num1'
    required: true
    default: 40 
  sum2:
    description: 'my num2'
    required: true
    default: 50
outputs:
  time:
    description: 'sum'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sum1 }}
    - ${{ inputs.sum2 }}
