name: 'My Docker GitHub Action'
description: 'A simple GitHub Action that runs inside a Docker container'
inputs:
  name:
    description: 'Name to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'  
  args:
    - ${{ user }}
    - ${{ surname }}
    #  entrypoint: './entrypoint.sh'
