on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      #      - name: checkout
      #  uses: actions/checkout@v4
      - name: clone
        run: git clone https://github.com/EdgarHarutyunyan2025/create_actions.git
      - name: list dir
        run: ls -la
      - name: Hello world action step
      - name: run docker
        run: docker run hello-world:latest
        uses: ./create_actions        #actions/hello-world-docker-action@v2
        with:
          port: '80:80'
          #name: 'actions'
          #      - name: Get the output time
          #run: echo "The time was ${{ steps.hello.outputs.time }}"
