on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      #      - name: checkout
      #  uses: actions/checkout@v4
      - name: clone
        run: git clone https://github.com/EdgarHarutyunyan2025/create_actions.git
      - name: list dir
        run: ls -la
      - name: Hello world action step
        uses: ./create_actions        #actions/hello-world-docker-action@v2
        with:
          sum1: 80
          sum2: 90
          #name: 'actions'
          #      - name: Get the output time
          #run: echo "The time was ${{ steps.hello.outputs.time }}"
