name: Test My Docker GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test_my_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: my acstion 
        uses: ./path/to/my-docker-action
        with:
          name: "John"
