name: Test My Docker GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test_my_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: pwd
        run: |
          pwd
          ls -la
      - name: my acstion 
        uses: ./
        with:
          args1: "github"
          args2: "actions"

